version: '3.7'

services:
  frontend:
    build:
      context: ./frontend/
    command: npm start
    container_name: minotaur_frontend
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    expose:
      - 3000
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend/
    ports:
      - '8525:8525'
    expose:
      - 8525